### ISSUE TITLE
Render custom html in chatbot window

### ISSUE THREAD

**Issue by eddykaya** [CSML-by-Clevy/csml-engine#237]
**Describe the solution you'd like**
I wonder if it is possible to render custom HTML in the chatbot window, e.g. a link tag or some custom javascript which is executed when clicking a button.

**Describe alternatives you've considered**
Manipulate the DOM based on some kind of CSS selector from the container web app

**Additional context**
I want to display a call us button in order to guide a user to the phone app on his/her device.

**Comment by frsechet** [comment]
Hi @eddykaya,

I'm guessing this question is about the Webapp of CSML Studio?

If yes, to get to the specific result you want, you can simply do something like: `say Url("tel:0123456789", text="Call Us")` which will automatically open the phone app on the user's device.

![IMG_1519](https://user-images.githubusercontent.com/7351940/110100259-7ff70080-7da2-11eb-82c5-6aec1ecc3162.jpg)

Otherwise, when using the CSML Engine directly (self-hosted or through the API channel of CSML Studio), you can use [Custom Components](https://docs.csml.dev/language/sending-receiving-messages/custom-components), or just add additional properties on any component you like and retrieve the value there, i.e:

```
say Text("Call Us", phone_number="0123456789")

// the output is:
{
  "content_type": "text",
  "content": {
    "text": "Call Us",
    "phone_number": "0123456789"
  }
}
```
Which you can handle exactly as you want in your application.

**Comment by eddykaya** [comment]
Thanks for your reply, I also figured out this solution. Is it possible to style the link like a button when using the webapp channel?

**Comment by frsechet** [comment]
Not currently.

For questions/requests about CSML Studio, consider joining the Slack community! https://csml.dev/slack
